<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>voicevox_speaker</name>
  <version>0.0.1</version>
  <description>
    ROS 2 package for generating Japanese speech with VOICEVOX and providing 
    lip-sync data for interactive agents.
  </description>
  <maintainer email="humansbadrobotsgood@gmail.com">tomicodev</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <!--sfml build deps-->
  <build_depend>libxrandr</build_depend>
  <build_depend>libxcursor-dev</build_depend>
  <build_depend>libxi-dev</build_depend>
  <build_depend>libudev-dev</build_depend>
  <build_depend>libflac-dev</build_depend>
  <build_depend>libvorbis-dev</build_depend>
  <build_depend>opengl</build_depend>
  <build_depend>libdrm-dev</build_depend>

  <!--audioquery support-->
  <build_depend>nlohmann-json-dev</build_depend>

  <depend>rclcpp</depend>
  <depend>rclcpp_lifecycle</depend>
  <depend>lifecycle_msgs</depend>
  <depend>rclcpp_action</depend>

  <depend>ament_index_cpp</depend>
  <depend>speaker_actions</depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
